### ISSUE TITLE
Support for roles and groups

### ISSUE THREAD

**Issue by darrenhaken** [betabandido/databricks-sdk-go#5]
Any appetite for this?

**Comment by darrenhaken** [comment]
Sorry, I didn't reply to this, it slipped through the cracks!

I had my AWS and Data Bricks worlds mixed up with groups and roles, ignore me :)
How's it coming along?

**Comment by betabandido** [comment]
Support for groups is already available in the SDK. See https://github.com/betabandido/databricks-sdk-go/blob/master/api/groups/endpoint.go

I will close this issue. Feel free to reopen it if you think something is missing.

**Comment by darrenhaken** [comment]
When will this be added to the TF provider?
